### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by sntgopl** [cvalencia1991/Leaderboard#3]
Good job so far, Cesar! Your code's looking great and has great functionality. Here are some suggestions that could improve your code or make it more friendly to the reading: 

- In index.js you can remove the `else` statement and use the declaration inside the `if` to call the class method.
- In the class methods, you could merge both in one so you just have to call one function for the same purpose.
- You can also create a new class instance when you call the event for submitting, giving it the variable values of the input values that were submitted.

**Comment by cvalencia1991** [comment]
ok i did thanks santiago
